### ISSUE TITLE
Emacs 29 breaks rfc-mode-forward-page

### ISSUE THREAD

**Issue by mattheww** [galdor/rfc-mode#22]
In Emacs 29, `rfc-mode-forward-page` usually leaves the position unchanged.

In particular, this happens if point is at the start of a line immediately before the `^L`, as it will be after using `rfc-mode-forward-page` once.

I think this is fallout from the changes made here:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=20663

https://git.savannah.gnu.org/cgit/emacs.git/commit/?id=3aaed2e1ccfcc230f813d3fe7867a7abc5b22109

**Comment by galdor** [comment]
I can reproduce the problem here. Let me see if I can fix it.

**Comment by galdor** [comment]
Fixed in v1.4.1 :)
