### ISSUE TITLE
Look for `.txt.gz` as well

### ISSUE THREAD

**Issue by vincentbernat** [galdor/rfc-mode#3]
Hey!

In Debian, there are RFC packages providing all the RFC in `/usr/share/doc/RFC/links`. They are gzip compressed. Would it be possible for rfc-mode to also looks for `rfcXXXX.txt.gz`?

Thanks!

**Comment by galdor** [comment]
Sorry for the lack of response, I did not receive any notification about your message.

It would make the code way more complicated  for virtually nothing (the entire set of RFC documents currently uses 568MB, 248MB if compressed, the economy in space isn't exactly staggering). I would suggest either copying the Debian directory and running `gunzip *.gz` or simply let `rfc-mode` download documents when they are needed.
