### ISSUE TITLE
helm-M-x-execute-command: Opening output file: No such file or directory, /Users/xxx/rfc/rfc-index.txt

### ISSUE THREAD

**Issue by kaiwk** [galdor/rfc-mode#4]
## Reproduce

1. remove `~/rfc/`
2. change `rfc-mode-directory` to anywhere except `~/rfc/`
3. restart emacs

## Tips
`setq` `rfc-mode-directory` before `require` this package can avoid this bug. The reason is that after `defvar` `rfc-mode-index-path`, change `rfc-mode-directory` won't modify `rfc-mode-index-path`, we'd better define `rfc-mode-index-path` as a function.

```elisp
(defun rfc-mode-index-path ()
 "The path of the file containing the index of all RFC documents."
 (concat rfc-mode-directory "rfc-index.txt"))
```

**Comment by galdor** [comment]
Sorry for the lack of response, I did not receive any notification about your message.

You are entirely right, I'm going to fix it.
