### ISSUE TITLE
rephrase README such that the on-demand download is mentioned

### ISSUE THREAD

**Issue by novoid** [galdor/rfc-mode#6]
Hi,

Thanks for this great project!

My issue: Currently, I would need to constantly spend 466MB for the txt-files alone on my synchronized computers (or accordingly for any sub-set of RFCs, of course).

_I'd like to send a letter to Santa Claus:_

To me, it would be perfect when this mode uses a local copy of the total index (1.8MB) for search. When I choose to read a specific RFC, the txt-version (or PDF?) should be fetched on-demand by rfc-mode in a temporary(?) directory for reading.

Using this idea would require just the 1.8MB of the index file for searching. The files in the local cache could be either permanent (locality of reference) or removed from time to time (e.g., by using a sub-directory of `/tmp/`).

**Comment by galdor** [comment]
Hi!

In the last version, RFC documents are downloaded on-demand, so it seems your
problem is solved :)

Feel free to ping me if it does not work as it should.

Regards,

-- 
Nicolas Martyanoff
http://snowsyn.net
khaelin@gmail.com

**Comment by novoid** [comment]
Oh I see.
Awesome!

Then let's change my issue to "rephrase README such that the on-demand download is mentioned and the bulk download is marked as optional" :-)

**Comment by galdor** [comment]
Good point, I'll fit it ASAP !

-- 
Nicolas Martyanoff
http://snowsyn.net
khaelin@gmail.com
